### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by zocom-david-lundholm** [sleam91/E-Wallet#1]
Klockrent Sebastian!

Tänk på:
* Undvik att använda javascript för att manipulera CSS så gott det går, det blir väldigt snabbt spagettikod när man blandar teknikerna. Använd istället class-binding och låt CSS:en styra stylen för de klasserna istället.

**Comment by sleam91** [comment]
Nu har jag förenklat card-CSS rätt mycket och tog bort en hel del duplicerad kod i olika views och komponenter, nu behövs det inte heller spara färgerna/chip i card-objekt och DB.
All styling för kort finns nu i card-component med hjälp av class-bind som du sa.
Det är enda stället där CSS finns kvar i script tag är i komponent CardStack där jag inte kunde lösa det utan CSS variabler och style-binding.
Tack för feedback!
